/**
 * Developer Guide Knowledge Base — Export utility
 *
 * Uses pre-bundled guide data from developer-guide-data.generated.ts
 * (generated by scripts/bundle-developer-guide.mjs).
 */

import { GUIDE_SECTIONS, GUIDE_SECTION_COUNT } from "./developer-guide-data.generated";

export { GUIDE_SECTION_COUNT };

const SEPARATOR = "\n\n---\n\n";

export interface ExportOptions {
  /** Chrome extension ID for path resolution */
  extensionId?: string;
  /** Project root path */
  projectRoot?: string;
  /** Project-specific context to prepend */
  projectContext?: {
    name: string;
    slug: string;
    codeName: string;
    version: string;
  };
}

/**
 * Concatenates all developer guide documents into a single markdown string
 * with resolved placeholders and optional project context header.
 */
export function exportKnowledgeBase(options: ExportOptions = {}): string {
  const header = buildHeader(options);
  const body = GUIDE_SECTIONS.join(SEPARATOR);
  const resolved = resolvePlaceholders(body, options);

  return header + resolved;
}

function buildHeader(options: ExportOptions): string {
  const lines: string[] = [
    "# Rise Up Macro — AI Knowledge Base",
    "",
    `> Exported: ${new Date().toISOString()}`,
  ];

  if (options.extensionId) {
    lines.push(`> Extension ID: ${options.extensionId}`);
  }

  if (options.projectContext) {
    const ctx = options.projectContext;
    lines.push(`> Project: ${ctx.name} (${ctx.slug}) v${ctx.version}`);
    lines.push(`> SDK Namespace: \`RiseupAsiaMacroExt.Projects.${ctx.codeName}\``);
  }

  lines.push("", "---", "", "");
  return lines.join("\n");
}

function resolvePlaceholders(content: string, options: ExportOptions): string {
  let resolved = content;

  if (options.extensionId) {
    resolved = resolved.replace(/\{EXTENSION_ID\}/g, options.extensionId);
  }

  if (options.projectRoot) {
    resolved = resolved.replace(/\{PROJECT_ROOT\}/g, options.projectRoot);
  }

  return resolved;
}
