/**
 * AUTO-GENERATED FALLBACK STUB.
 *
 * The real contents of this file are produced by
 * `node scripts/bundle-developer-guide.mjs` during the build pipeline and
 * contain the bundled markdown for the Developer Guide AI knowledge base.
 *
 * This stub exists ONLY so:
 *   1. The TypeScript compiler can resolve `./developer-guide-data.generated`
 *      from `src/lib/developer-guide-bundle.ts` on a fresh checkout where
 *      the bundler has not yet run (the real generated file is gitignored).
 *   2. The web-app preview build does not crash before
 *      `scripts/bundle-developer-guide.mjs` runs.
 *
 * Do NOT edit this file by hand. Run the bundler to populate it for real.
 */

export const GUIDE_SECTIONS: string[] = [];
export const GUIDE_SECTION_COUNT = 0;
